version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
  redis:
    image: redis:alpine
    command: redis-server --requirepass test
    ports:
    - "6379:6379"
